### ISSUE TITLE
Roundcube doesn't load

### ISSUE THREAD

**Issue by aalcaine** [g0dsCookie/imap_labels#1]
After enabling the plugin cannot access webmail.nnnnnnn.com , a "Could not load page" message appears from the browser.
Tested with Opera and Safari. :(

**Comment by g0dsCookie** [comment]
Don't have time to debug and fix this, sorry. This was a project which I started in my spare time which I never finished as I'm not that PHP guy.

Maybe theres someone with some spare time who is willing to debug and fix this. Maybe even I will find time for this.

**Comment by g0dsCookie** [comment]
Could you please post the roundcube version you are using?

**Comment by aalcaine** [comment]
Oh, don't worry! Was just to comment that there's an issue.
I'm using Roundcube Webmail 1.2.7 :)

**Comment by g0dsCookie** [comment]
My last commit in master should fix your issue.
